### PR TITLE
update CSS and javascript

### PR DESCRIPTION
**Pull request by ASlayton**
Check the suck it page, image should be centered and background should be black

### CODE REVIEW

**Comment by aprilrochelle** [comment]
H1 on songs page should be Sentence Case
Looks like this branch doesn't have the current master merged in

**Comment by aprilrochelle** [comment]
Suck It page is great tho!

**Comment by maryaliceorr** [comment]
suck it page looks great, but band members page is now missing the music note border and the the favorite song is gone on each band member.

**Comment by amillion3** [comment]
I don't see the music notes border either.

👍

**Comment by amillion3** [comment]
Something else I noticed... on the branch as-fix-suckit, on the index page, the mini-tour displays the shows, twice. However, on the main branch, it only shows the 3 shows, like it should. Weird

**Comment by ASlayton** [comment]
This branch did not include the last 2 branches changes, it was only the change to suck it page

**Comment by aprilrochelle** [comment]
👍 GREAT!

**Comment by nathanpabst** [comment]
👍 
💯 love this

**Pull request merged**
