### PR TITLE
Mao thingsleft

### PR DESCRIPTION
**Pull request by maryaliceorr**

### CODE REVIEW

**Review by amillion3 — COMMENTED** [review]
main.js line 64, I think we decided to use the writeToDom and not printToDom function. Please delete printToDom function as well, thanks.

**Comment by ASlayton** [comment]
👍

**Comment by aprilrochelle** [comment]
Take display flex off the header

**Comment by amillion3** [comment]
👍

**Comment by aprilrochelle** [comment]
👍

**Pull request merged**
